accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView,)
from .views import *
from main.views import my_attendance
app_name = 'accounts'
urlpatterns = [
    path('sign_up/', MySignUpView.as_view(), name='sign_up'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
	path('profile/',my_attendance),]

automated_attendance/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import my_attendance

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('app/',include('main.urls')),
	path('',my_attendance, name="home"),
]

main/urls.py
from django.urls import path
from .views import *
app_name = 'main'
urlpatterns = [
    path('',my_attendance, name='home'),
    path('upload_image_html/', upload_image_html, name="upload_image_html"),
    path('upload_image_logic/', upload_image_logic, name="upload_image_logic"),
    path('feed_attendance_html/', feed_attendance_html, name="feed_attendance_html"),
    path('feed_attendance_logic/', feed_attendance_logic, name="feed_attendance_logic"),
    path('my_attendance/',my_attendance,name='my_attendance'),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class ImageUploaded(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	
	def __str__(self):
		return str(self.user.username)

class Attendance(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.CharField(max_length = 100)
	status = models.BooleanField()
	def __str__(self):
		return str(self.user.username)+' : '+str(self.date)

accounts/views.py
from django.shortcuts import render
from django.http import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views import View
from django.contrib.auth import login


class MySignUpView(View):
    form_class = UserCreationForm
    template_name = 'accounts/sign_up.html'
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            u = User.objects.create_user(
                    username=form.cleaned_data.get('username'),
                    password=form.cleaned_data.get('password1'),
		    email = form.cleaned_data.get('email'),
                    is_active = True
            )
            login(request,u)
            # TODO Display message and redirect to login
            return HttpResponseRedirect('/')
        return render(request, self.template_name, {'form': form})

main/views.py
from django.shortcuts import render
from .models import ImageUploaded, Attendance
from django.core.files.storage import FileSystemStorage
from .face_extractor import face_extract as fe
from .face_recognizer import face_recognize as fr
import os
import shutil
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
import datetime
import pytz
import smtplib 

# Create your views here.
@login_required
def upload_image_html(request):
	qSet = ImageUploaded.objects.filter(user=request.user)
	if len(qSet) == 0:
		return render(request,'main/upload_image_html.html',{})
	qSet = Attendance.objects.filter(user=request.user)
	return render(request,'main/my_attendance.html',{'data':qSet})
	
@login_required
def upload_image_logic(request):
	image = request.FILES['image']
	fs = FileSystemStorage()
	filename = fs.save('main/known_faces/'+str(request.user.username)+'.jpg', image)
	obj = ImageUploaded(user=request.user)
	obj.save()
	qSet = Attendance.objects.filter(user=request.user)
	return render(request,'main/my_attendance.html',{'data':qSet})

@login_required
def my_attendance(request):
	qSet = ImageUploaded.objects.filter(user=request.user)
	if len(qSet) == 0:
		return render(request,'main/upload_image_html.html',{})
	qSet = Attendance.objects.filter(user=request.user)
	return render(request,'main/my_attendance.html',{'data':qSet})

@staff_member_required
def feed_attendance_html(request):
	if request.user.is_superuser:
		return render(request,'main/feed_attendance_html.html',{})
	qSet = Attendance.objects.filter(user=request.user)
	return render(request,'main/my_attendance.html',{'data':qSet})
	
@staff_member_required
def feed_attendance_logic(request):
	if request.user.is_superuser:
		image = request.FILES['image']
		fs = FileSystemStorage()
		shutil.rmtree('main/camera')
		os.mkdir('main/camera')
		filename = fs.save('main/camera/camera_snap.jpg', image)
		fe()
		usernames = fr()
		qSet = User.objects.all()
		now = datetime.datetime.now()
		tz = pytz.timezone('Asia/Kolkata')
		now = now.astimezone(tz)
		date_string = now.strftime("%d/%m/%Y %H:%M:%S")
 
		for user in qSet:
			print('sending emails.....')
			if user.username in usernames:
				obj = Attendance(user=user,date=date_string,status=True)
				obj.save()
				message = "\nHello, "+user.username+" Attendace marked as present on "+date_string
				print(message)
				s = smtplib.SMTP('smtp.gmail.com', 587) 
				s.starttls() 
				s.login("vaishnavmajor@gmail.com", "--c2-0-0") 
				s.sendmail("vaishnavmajor@gmail.com", user.email, message) 
				s.quit()
			else:
				obj = Attendance(user=user,date=date_string,status=False)
				obj.save()
				message = "\nHello, "+user.username+" Attendace marked as absent on "+date_string
				print(message)
				s = smtplib.SMTP('smtp.gmail.com', 587) 
				s.starttls() 
				s.login("vaishnavmajor@gmail.com", "--c2-0-0") 
				s.sendmail("vaishnavmajor@gmail.com", user.email, message) 
				s.quit()
			
	qSet = Attendance.objects.filter(user=request.user)
	return render(request,'main/my_attendance.html',{'data':qSet})

accounts/templates/accounts/login.html
{% load staticfiles %}
<head>
    <title>Sign In</title>
<style type="text/css">
        body
{
  margin:0;
  padding:0;
  font-family: 'Ubuntu', sans-serif;
  align-items:center;
  height:100vh;
  background: url("{% static 'images/accounts_bg.jpg' %}");
}
.login
{
  text-align:center;
  width:350px;
  border-radius:20px;
  box-sizing:border-box;
  padding:40px;
  background:#000000;
    background: rgba(0, 0, 0, 0.7);
  position:absolute;
  top:50%;
  left:50%;
  transform:translate(-50%,-50%);
}
.login h2
{
  margin: 0 0 20px;
  padding:0;
  font-size:30px;
  text-transform:uppercase;
  color: white;
}
.login .input-group
{
  position:relative;
  width:100%;
  margin-bottom:25px;
    box-shadow: none;
}
.login .input-group input
{
  height:50px;
  width:100%;
  box-sizing:border-box;
  font-size:18px;
  outline:none;
  border:1px solid #000;
  border-radius:20px;
  padding-left:20px;
  padding-right:30px;
}


.login .input-group input[type="submit"]
{
  background:#279CEB;
  border:none;
  box-shadow: none;
  cursor:pointer;
  font-wight:600;
  text-transform:uppercase;
  color:#fff;
}
.login .input-group input[type="submit"]:hover
{
  background:#31a9f9;
}
.login a
{
  font-size:12px;
  color:white;
  text-decoration:none;
  display:block;
  text-align:center;

}
.login a span
{
  color:#262626;
  font-weight:600;
}
.login a span:hover
{
  color:#ffc107;
}
.login span{
    color:white;
}
</style>
</head>

{%if user.is_authenticated %}
    <script>window.location.replace("{% url 'home' %}");</script>
{% endif %}

{% block content %}
    <body>
<div class="login">
    {% if next %}
        {% if user.is_authenticated %}
            <p style="color: #FF3A3A">Your account doesn't have access.</p>
        {% else %}
            <p style="color: #FF3A3A">Please login to see this page.</p>
        {% endif %}
    {% endif %}
  <h2>Sign In</h2>
  <form method="post" action="{% url 'accounts:login' %}">
      {% csrf_token %}
    <div class="input-group">
      <input type="text" name="username" id="id_username" required placeholder="Username">
    </div>
    <div class="input-group">
      <input type="password" name="password" required id="id_password" placeholder="Password">
    </div>
    <div class="input-group">
      <input type="submit" value="login">
        <input type="hidden" name="next" value="{{ next }}" />
    </div>
   </form>
    <div class="input-group">
    <span><a href="{% url 'accounts:sign_up' %}">Don't have an Account?</a></span>
    </div>
        {% if form.errors %}
        <p style="color: #FF3A3A">Failed! Login with correct credentials.</p>
    {% endif %}
</div>
</body>
{% endblock %}

accounts/templates/accounts/logout.html
{% block content %}
    <script>window.location.replace("{% url 'accounts:login' %}");</script>
  <div class="container">
      <div class="row justify-content-center align-items-center" style="height:80vh;">
          <div class="col-auto border p-3">
              You are logged out
          </div>
      </div>
  </div>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% load staticfiles %}
<head>
    <title>Sign Up</title>
<style type="text/css">
        body
{
  margin:0;
  padding:0;
  font-family: 'Ubuntu', sans-serif;
  align-items:center;
  height:100vh;
  background: url("{% static 'images/accounts_bg.jpg' %}");
}
.login
{
  text-align:center;
  width:350px;
  border-radius:20px;
  box-sizing:border-box;
  padding:40px;
  background:#000000;
    background: rgba(0, 0, 0, 0.7);
  position:absolute;
  top:50%;
  left:50%;
  transform:translate(-50%,-50%);
}
.login h2
{
  margin: 0 0 20px;
  padding:0;
  font-size:30px;
  text-transform:uppercase;
  color: white;
}
.login .input-group
{
  position:relative;
  width:100%;
  margin-bottom:25px;
    box-shadow: none;
}
.login .input-group input
{
  height:50px;
  width:100%;
  box-sizing:border-box;
  font-size:18px;
  outline:none;
  border:1px solid #000;
  border-radius:20px;
  padding-left:20px;
  padding-right:30px;
}


.login .input-group input[type="submit"]
{
  background:#279CEB;
  border:none;
  box-shadow: none;
  cursor:pointer;
  font-wight:600;
  text-transform:uppercase;
  color:#fff;
}
.login .input-group input[type="submit"]:hover
{
  background:#31a9f9;
}
.login a
{
  font-size:12px;
  color:white;
  text-decoration:none;
  display:block;
  text-align:center;

}
.login a span
{
  color:#262626;
  font-weight:600;
}
.login a span:hover
{
  color:#ffc107;
}
.login span{
    color:white;
}
        .helptext{
            color: #279CEB;
        }
    .ul li{
        color: white;
    }
</style>
</head>
{%if user.is_authenticated %}
    <script>window.location.replace("{% url 'home' %}");</script>
{% endif %}
<body>
{% block content %}
<div class="login">
  <h2>Sign Up</h2>
  <form method="post" action="">
      {% csrf_token %}
    <div class="input-group">
      <input type="text" name="username" required id="id_username" placeholder="Username">
    </div>
    <div class="input-group">
      <input type="text" name="email" required id="id_email" placeholder="Email">
    </div>
    <div class="input-group">
      <input type="password" name="password1" required id="id_password1" placeholder="Password">
    </div>
       <div class="input-group">
      <input type="password" name="password2" required id="id_password2" placeholder=" Confirm Password">
    </div>
    <div class="input-group">
      <input type="submit" value="Submit">
        <input type="hidden" name="next" value="" />
    </div>
   </form>
    <div class="input-group">
    <span><a href="{% url 'accounts:login' %}">Already have an Account?</a></span>
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p style="color: #FF3A3A">{{ error}}</p>
            {% endfor %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}
</body>

main/templates/main/feed_attendance_html.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Feed New Attendance</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'app/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'app/css/grayscale.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">

</head>

<body id="page-top">

  <!-- Navigation -->
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{%url 'home'%}">
      <img src="{% static 'app/img/logo.png' %}" width="448" height="28">
    </a>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
	{%if request.user.is_staff%}
          <a class="button is-primary" href="{% url 'main:feed_attendance_html' %}">
            <strong>Feed New Attendance</strong>
          </a>
	{%endif%}
          <a class="button is-light is-danger" href="{% url 'accounts:logout' %}">
            Logout | {{request.user.username}}
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>
  <!-- Header -->
  <header class="masthead">
<p style="padding:25px; color:#ffffff; font-size:32px;">Upload the class photograph for feeding the attendance</p>
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center" style="background:#ffffff;padding:10px; border-radius:10px">
	<form action="{% url 'main:feed_attendance_logic'%}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="file" name="image"></input></br>
	<input type="submit" style="margin-top:10px"class="button is-primary"></input>
	</form>
	</div>
    </div>
  </header>

  <!-- About Section -->
  


  <!-- Signup Section -->
  

  <!-- Contact Section -->
  

  <!-- Footer -->
  

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'app/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'app/js/grayscale.min.js' %}"></script>

</body>

</html>

main/templates/main/my_attendance.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Attendance | Records</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'app/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'app/css/grayscale.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">

</head>

<body id="page-top">

  <!-- Navigation -->
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{%url 'home'%}">
      <img src="{% static 'app/img/logo.png' %}" width="448" height="28">
    </a>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
	{%if request.user.is_staff%}
          <a class="button is-primary" href="{% url 'main:feed_attendance_html' %}">
            <strong>Feed New Attendance</strong>
          </a>
	{%endif%}
          <a class="button is-light is-danger" href="{% url 'accounts:logout' %}">
            Logout | {{request.user.username}}
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

  <!-- Header -->
  <header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
<table border=2px style="background:white;">
<tr>
<td>S.No</td>
<td>Date & Time</td>
<td>Status</td>
</tr>
{%for attendance in data%}
<tr>
<td>{{forloop.counter}}</td>
<td>{{attendance.date}}</td>
{% if attendance.status%}
<td style="background:#4bb543;">Present</td>
{%else%}
<td style="background:red;">Absent</td>
{%endif%}
{%endfor%}
</tr>
</table>
</div>
    </div>
  </header>

  <!-- About Section -->
  


  <!-- Signup Section -->
  

  <!-- Contact Section -->
  

  <!-- Footer -->
  

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'app/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'app/js/grayscale.min.js' %}"></script>

</body>

</html>

main/templates/main/upload_image_html.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Upload your photo</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'app/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'app/css/grayscale.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">

</head>

<body id="page-top">

  <!-- Navigation -->
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{%url 'home'%}">
      <img src="{% static 'app/img/logo.png' %}" width="448" height="28">
    </a>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
	{%if request.user.is_staff%}
          <a class="button is-primary" href="{% url 'main:feed_attendance_html' %}">
            <strong>Feed New Attendance</strong>
          </a>
	{%endif%}
          <a class="button is-light is-danger" href="{% url 'accounts:logout' %}">
            Logout | {{request.user.username}}
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

  <!-- Header -->
  <header class="masthead">
   <p style="padding:25px; color:#ffffff; font-size:32px;">Complete the registration by uploading your photograph</p>	
    <div class="container d-flex h-100 align-items-center">
	<h2>Hello</h2>
      <div class="mx-auto text-center" style="background:#ffffff;padding:10px; border-radius:10px">
	<form action="{% url 'main:upload_image_logic'%}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="file" name="image"></input><br/>
	<input type="submit" style="margin-top:10px"class="button is-primary"></input>
	</form>
	</div>
    </div>
  </header>

  <!-- About Section -->
  


  <!-- Signup Section -->
  

  <!-- Contact Section -->
  

  <!-- Footer -->
  

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'app/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'app/js/grayscale.min.js' %}"></script>

</body>

</html>